<a href="https://colab.research.google.com/github/ffufd0520-hash/linear-algebra/blob/main/%ED%96%89%EB%A0%AC%EC%8B%9D%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

A = np.array([
    [2,1,3,4],
    [0,1,1,0],
    [1,0,1,1],
    [4,2,1,-1]
], dtype=int)

original_A = A.copy()
swap_count= 0

def show(step,matrix):
  print(f"\n{step}")
  print(matrix)

show("초기 행렬 A",A)

#1. R1과 R3 교환
A[[0,2]] = A[[2,0]]
swap_count += 1
show("1단계: R1<->R3",A)

#2. 첫 번째 열의 아래쪽 원소를 0으로 만듦
A[2] = A[2] - 2 * A[0] #R3 <- R3 - 2R1
show("2단계: R3 <- R3 - 2R1",A)

A[3] = A[3] - 4 * A[0] #R4 <- R4 - 4R1
show("3단계: R4 <- R4 - 4R1",A)

#3. 두 번째 열의 아래쪽 원소를 0으로 만듦
A[2] = A[2] - A[1] #R3 <- R3 - R2
show("4단계: R3 <- R3 - R2",A)

A[3] = A[3] - 2 * A[1] #R4 <- R4 - 2R2
show("5단계: R4 <- R4 - 2R2",A)

#4. 피벗 위치를 맞추기 우해 R3과 R4 교환
A[[2,3]] = A[[3,2]]
swap_count += 1
show("6단계: R3<->R4",A)

#상삼각행렬의 대각 원소 곱
diagonal_product = np.prod(np.diag(A))

# 행 교환이 일어날 때마다 행렬식의 부호가 바뀜
det_A = ((-1) ** swap_count) * diagonal_product
print("\n행 사다리꼴")
print(A)

print("\n대각 원소의 곱", diagonal_product)
print("행 교환 횟수", swap_count)
print("det(A) = ", det_A)

# Numpy 계산 결과와 비교
det_check = round(np.linalg.det(original_A))
print("Numpy 검산 결과", det_check)


초기 행렬 A
[[ 2  1  3  4]
 [ 0  1  1  0]
 [ 1  0  1  1]
 [ 4  2  1 -1]]

1단계: R1<->R3
[[ 1  0  1  1]
 [ 0  1  1  0]
 [ 2  1  3  4]
 [ 4  2  1 -1]]

2단계: R3 <- R3 - 2R1
[[ 1  0  1  1]
 [ 0  1  1  0]
 [ 0  1  1  2]
 [ 4  2  1 -1]]

3단계: R4 <- R4 - 4R1
[[ 1  0  1  1]
 [ 0  1  1  0]
 [ 0  1  1  2]
 [ 0  2 -3 -5]]

4단계: R3 <- R3 - R2
[[ 1  0  1  1]
 [ 0  1  1  0]
 [ 0  0  0  2]
 [ 0  2 -3 -5]]

5단계: R4 <- R4 - 2R2
[[ 1  0  1  1]
 [ 0  1  1  0]
 [ 0  0  0  2]
 [ 0  0 -5 -5]]

6단계: R3<->R4
[[ 1  0  1  1]
 [ 0  1  1  0]
 [ 0  0 -5 -5]
 [ 0  0  0  2]]

행 사다리꼴
[[ 1  0  1  1]
 [ 0  1  1  0]
 [ 0  0 -5 -5]
 [ 0  0  0  2]]

대각 원소의 곱 -10
행 교환 횟수 2
det(A) =  -10
Numpy 검산 결과 -10


In [4]:
import numpy as np

A = np.array([
    [1,0,2],
    [2,-1,3],
    [4,1,8]
])

B = np.array([
    [11,2,2],
    [-4,0,1],
    [6,-1,-1]
])

# 3x3 단위행렬
I = np.eye(3,dtype=int)

# 행렬곱 계산
AB = A @ B
BA = B @ A

print("A =")
print(A)

print("\nB =")
print(B)

print("\nAB =")
print(AB)

print("\nBA =")
print(BA)

#단위행렬과 같은지 확인
print("\nAB = l :",np.array_equal(AB,I))
print("BA = l :",np.array_equal(BA,I))

if np.array_equal(AB, I) and np.array_equal(BA, I):
  print("\nA와 B는 서로 역행렬입니다.")
  print("즉, B = A^-1이고 A = B^-1입니다.")
else:
  print("\ㅜA와 B는 서로 역행렬이 아닙니다.")


A =
[[ 1  0  2]
 [ 2 -1  3]
 [ 4  1  8]]

B =
[[11  2  2]
 [-4  0  1]
 [ 6 -1 -1]]

AB =
[[23  0  0]
 [44  1  0]
 [88  0  1]]

BA =
[[23  0 44]
 [ 0  1  0]
 [ 0  0  1]]

AB = l : False
BA = l : False
\ㅜA와 B는 서로 역행렬이 아닙니다.


In [7]:
import numpy as np
#행렬 정의
A = np.array([
    [1,2],
    [1,3]
],dtype=float)

B = np.array([
    [3,2],
    [2,2]
],dtype=float)

#각각의 역행렬
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

#행렬곱 AB
AB = A @ B

#식의 왼쪽: (AB)^-1
left = np.linalg.inv(AB)

#식의 오른쪽: B^-1 A^-1
right = B_inv @ A_inv

np.set_printoptions(precision=3, suppress=True)


print("A^-1 =")
print(A_inv)

print("\nB^-1 =")
print(B_inv)

print("\nAB =")
print(AB)
print("\n(AB)^-1 =")
print(left)
print("\nB^-1 A^-1 =")
print(right)
# 두 결과가 같은지 확인
print("\n(AB)^-1 = B^-1 A^-1 인가?")
print(np.allclose(left, right))

A^-1 =
[[ 3. -2.]
 [-1.  1.]]

B^-1 =
[[ 1.  -1. ]
 [-1.   1.5]]

AB =
[[7. 6.]
 [9. 8.]]

(AB)^-1 =
[[ 4.  -3. ]
 [-4.5  3.5]]

B^-1 A^-1 =
[[ 4.  -3. ]
 [-4.5  3.5]]

(AB)^-1 = B^-1 A^-1 인가?
True


In [8]:
from fractions import Fraction

def print_augmented(title, matrix):
  """첨기행렬 [A I I]를 출력하는 함수"""
  print(f"\n{title}")

  for row in matrix:
    left = "  ".join(f"{str(x):>4}" for x in row[:2])
    right = "  ".join(f"{str(x):>4}" for x in row[2:])
    print(f"[ {left} I {right}]")

  #행렬 A와 단위행렬 I로 첨가행렬 구성
augmented = [
    [Fraction(3), Fraction(4), Fraction(1), Fraction(0)],
    [Fraction(2), Fraction(3), Fraction(0), Fraction(1)]
  ]

print_augmented("초기 첨가행렬 [A I I]", augmented)

#1단계: R1을 3으로 나눔
#(1/3)R1 -> R1
augmented[0] = [
    value / 3 for value in augmented[0]
]
print_augmented("1단계: R1을 3으로 나눔", augmented)
#2단계: 첫 번째 열의 2를 0으로 만듦
#R2 - 2R1-> R2
augmented[1] = [
    augmented[1][j] - 2 * augmented[0][j]
    for j in range(4)
]

#3단계: 두 번째 피벗을 1로 만듦
#3R2 -> R2
augmented[1] = [
    3 * value for value in augmented[1]
]
print_augmented("3단계: 3R2 -> R2 ", augmented)

#4단계: 첫 번째 행의 4/3을 0으로 만듦
#R1 - (4/3)R2-> R1
augmented[0] = [
    augmented[0][j] - Fraction(4,3) * augmented[1][j]
    for j in range(4)
]
print_augmented("4단계: R1 - (4/3)R2-> R1", augmented)

#오른쪽 부분이 역행렬
A_inverse = [
    row[2:] for row in augmented
]

print("\n의 역행렬:")
for row in A_inverse:
  print([str(value) for value in row])



초기 첨가행렬 [A I I]
[    3     4 I    1     0]
[    2     3 I    0     1]

1단계: R1을 3으로 나눔
[    1   4/3 I  1/3     0]
[    2     3 I    0     1]

3단계: 3R2 -> R2 
[    1   4/3 I  1/3     0]
[    0     1 I   -2     3]

4단계: R1 - (4/3)R2-> R1
[    1     0 I    3    -4]
[    0     1 I   -2     3]

의 역행렬:
['3', '-4']
['-2', '3']
